version: "3.8"

services:

  back-end:
    container_name: back-end-container
    build: ./back_end_trees/
    volumes: 
      - ./back_end_trees:/app
    restart: on-failure
    environment:
      DB_PWD: ${DB_PWD}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
    ports: 
      - 21452:21452
    command: bash -c "npm install && nodemon index.js"

  mariadb:
    container_name: mariadb-container
    image: mariadb
    volumes: 
      - ./db_store:/var/lib/mysql
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PWD}
    ports: 
      - 3306:3306

  nginx:
    container_name: nginx-container
    image: nginx
    volumes:
      - ./front_end_trees/build:/data/www:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: on-failure
    ports:
     - "80:80"
    environment:
    # - NGINX_HOST=foobar.com
     - NGINX_PORT=80

  # comment out in deployment!
  front-end-development:
    container_name: front-end-development-container
    build: ./front_end_trees/
    environment:
      PORT: 21451
    volumes: 
      - ./front_end_trees:/app
    restart: on-failure
    ports: 
      - 21451:21451
    command: bash -c "npm install && npm run start"

