version: "3.8"

services:
  #  back-end:
  #    container_name: blog-back-end
  #    build: ./back-end/
  #    volumes: 
  #      - ./back-end:/app
  #    ports: 
  #      - 21452:21452
  #    command: cargo watch -x check -x test -x run 

  front-end:
    container_name: front-end-container
    build: ./front_end_trees/
    environment:
      PORT: 21451
    volumes: 
      - ./front_end_trees:/app
    ports: 
      - 21451:21451
    command: bash -c "npm install && npm run start"

  mariadb:
    container_name: trees-container
    image: mariadb
    volumes: 
      - ./db_store:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: hawthorn
    ports: 
      - 3306:3306
